CREATE VIEW CustRep_Rider_View(RIDER_ID, WALLET_ID, NAME, PHONE_NUM, EMAIL, ADDRESS, ECOINS, NUM_MAINTAIN_ISSUES, NUM_COMPLAINTS)
  AS
    SELECT R.RIDER_ID,
           R.WALLET_ID,
           R.NAME,
           R.PHONE_NUM,
           R.EMAIL,
           R.ADDRESS,
           R.ECOINS,
           COUNT(MI.RIDER_ID),
           COUNT(C.RIDER_ID)
    FROM RIDER R FULL
           JOIN MAINTENANCE_ISSUE MI ON R.RIDER_ID = MI.RIDER_ID FULL
           JOIN COMPLAINT C ON C.RIDER_ID = R.RIDER_ID
    GROUP BY R.RIDER_ID, R.WALLET_ID, R.NAME, R.PHONE_NUM, R.EMAIL, R.ADDRESS, R.ECOINS;

CREATE VIEW Rider_Bike_View(bike_ID, latitude, longitude)
  AS
    SELECT bike_ID, latitude, longitude
    FROM Bike b
    WHERE b.is_broken = 'Y';

CREATE VIEW Available_Bikes_For_Rent(BIKE_ID, LATITUDE, LOGITUDE)
  AS
    SELECT B.BIKE_ID, B.LATITUDE, B.LONGITUDE
    FROM BIKE B
           LEFT JOIN TRIP T ON B.BIKE_ID = T.BIKE_ID
    WHERE B.IS_BROKEN = 'N'
      AND ((START_DATETIME IS NOT NULL AND END_DATETIME IS NOT NULL) OR START_DATETIME IS NULL);

COMMIT;